### ISSUE TITLE
ABI impl. difference between encoding empty strings in Dart vs Go

### ISSUE THREAD

**Issue by KingGorrin** [hypercore-one/znn_sdk_dart#1]
**Describe the bug**

The ABI impl. differs between Dart and Go when encoding an ABI function with empty strings arguments.

**To Reproduce**

## Dart

// Encoded empty string
`1b043f54000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

// Encoded "Hello World!" string
`1b043f540000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c48656c6c6f20576f726c64210000000000000000000000000000000000000000`

// The code to reproduce the results
``` dart
import 'package:hex/hex.dart';
import 'package:znn_sdk_dart/src/abi/abi.dart';

Future<void> main() async {
  var definition = Abi.fromJson(
    '''[{"type":"function","name":"Test","inputs":[
        {"name":"value","type":"string"}
      ]}]''');

  print(HEX.encode(definition.encodeFunction("Test", [""])));
  print(HEX.encode(definition.encodeFunction("Test", ["Hello World!"])));
}
```

## Go

// Encoded empty string
`1b043f5400000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000`

// Encoded "Hello World!" string
`1b043f540000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c48656c6c6f20576f726c64210000000000000000000000000000000000000000`

// The code to reproduce the results
``` go
package main

import (
	"encoding/hex"
	"fmt"
	"strings"
	"github.com/zenon-network/go-zenon/vm/abi"
)

const (
	jsonPack = `
	[{"type":"function","name":"Test","inputs":[
			{"name":"value","type":"string"}
		]}
	]`
)

var (
	ABIMock = abi.JSONToABIContract(strings.NewReader(jsonPack))
)

func main() {
	data1, _ := ABIMock.PackMethod("Test", "")
	data2, _ := ABIMock.PackMethod("Test", "Hello World!")

	fmt.Println(hex.EncodeToString(data1))
	fmt.Println(hex.EncodeToString(data2))
}
```

**Expected behavior**

The Go implementation uses a more efficient way of handling empty strings. The Dart impl. needs to be adjusted to match the same behaviour as the Go impl.

**Additional context**

It is still uncertain how the ABI specification describes the handling of empty strings and whether this is consistent with the Go impl.

**Comment by KingGorrin** [comment]
Reading the latest version of the [Formal Specification of the Encoding](https://docs.soliditylang.org/en/latest/abi-spec.html#formal-specification-of-the-encoding) it looks like empty strings should be padded with trailing zero-bytes to a length of 32 bytes.

But, these two Online ABI Encoders yield the same result as the Go impl.

- https://abi.hashex.org/
- https://adibas03.github.io/

Although I cannot exactly find it in the Formal Specification of the Encoding, the Go impl is probably the correct one.

**Comment by sol-znn** [comment]
Background
```
The go-sdk truncates the two empty strings. While the C# and Dart SDK do not.

BridgeApi.ChangeTssECDSAPubKey("AnecDxNfn2FeJroQeBxjnW1Jcdc/o+xPyTGTRfxcUcHy", "", "")

The method succeeds when using two values.

BridgeApi.ChangeTssECDSAPubKey("AnecDxNfn2FeJroQeBxjnW1Jcdc/o+xPyTGTRfxcUcHy", "1", "1")
```

**Comment by KingGorrin** [comment]
The AZ `UpdatePhase` method is also affected by this bug when trying to update a phase with an empty description.
